### PR TITLE
Major modification, how I can contribute?

### PR DESCRIPTION
**Pull request by wongchichong**
Hi, 

I like this project a lot, more then solid, without babel.
I've fork it 2 weeks ago to make it work in web worker, and it is working now.

Please clone this, it a monorepo/metarepo workspace used pnpm
https://github.com/wongchichong/meta-voby

follow instruction in meta-voby/readme.md, to install all packages, node_modules.
Packages configuration located in .meta, pnpm-workspace.yaml, and package.json workspaces entry.

I had remove those ~/ because having conflict with workspace
Use vite+esbuild & tsc instead of tsex because generating wrong output for eg. `import './jsx\types';`
Major patched in voby are in those files named with xxx.via.ts or xxx.ssr.ts.

To work in dom environment:
```ts
import {} from 'voby'
```

To work in worker environment:
`import {} from 'voby/via`

with tsconfig.json :
```ts
  "jsx": "preserve",
  "jsxImportSource": "voby/via",
```

Both runtimes stated in package.json exports entry.

Replicating voby demos into voby-via-demo in webworker context, excluding SSR, Portal, templates, capture, passive, propagate event, for more info, please run dev:playground in demo folder.

Roadmap (maybe):
A converter to convert major libraries (mui/antd) from react to voby (like https://github.com/swordev/suid)
Support @emotion/styling library or alternative **without babel**. 

via/web worker with above excluding features (KIV, low priority)

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Hi! This PR is way too big and cannot just be merged.

> Use vite+esbuild & tsc instead of tsex because generating wrong output for eg. import './jsx\types';

Are you under Windows? It sounds like there's a bug in `tsex` I should fix.

> To work in worker environment:
> import {} from 'voby/via

What did you do to make it "work" under a webworker environment? Like without shimming the DOM it cannot work exactly the same, and by shimming the DOM it seems to mostly [work](https://github.com/vobyjs/voby/blob/46d0426d6e08a25c7d8a8819632291cc7bc02e19/demo/ssr_esbuild/server/index.tsx#L4) under SSR too .

**Comment by wongchichong** [comment]
Hi,

I was thinking can you use my source as base to replace yours, and we both working from there.

I'm using windows.

I know is too big PR, just 2 weeks, because having project structure reorganized.

Yes, it working in DOM environment, you can load the meta-voby, build the packages in sequence (because the following packages need symlink reference, power of pnpm)

Run every demos in voby-via-demo beside uibench. All works including svg in web worker environment, vite is a must to load workers like webpack (webpack is too slow, and i just change to vite+esbuild).

Other SSR concept is about renderToString, but our SSR is about installing a web worker liked service on the server side, and RPC-ing with browser DOM, events are executed on the server.

pnpm run dev:playground 

is a good good place to start.

It even fixed some of the voby-demo test cases (i load 2  tabs to check what entity should change, LOL)

The big array benchmark, is not optimized (dev:benchmark), but it works. I so shame that I can't understand  the diff, and templates function. But I used empty textNode DOM as bookmark to track what I should replace.

The side effect are, some primitive observable must be bound using DIV or Span. The components effected so far are ternary, IF, ErrorBoundary...

I seeking opinions how should handle this.

Wrapping all components in components folder or wrap it by user if it is used. This can be seen in dev:playground too, understand /* bound  comment.




Get BlueMail for Android

**Comment by fabiospampinato** [comment]
Alright tsex v2.2.3 should fix the issue with imports.

I'd recommend to do the following first of all:

1. Revert all the changed `~/*` imports, I don't want those replaced with relative imports.
2. Revert all the changes in formatting, I don't want that to change (unless I've missed a semicolon somewhere or something).
3. Revert reorganizations that aren't strictly necessary, if needed they can be merged in other PRs.

Then:

1. If the resulting PR is understandable, i.e. not everything is changed so I can make sense of what the actually interesting changes are, I can see if it can make sense to merge it (unlikely, it seems pretty big regardless) or if I can extract some useful changes from it (possible).
2. Alternatively a better approach would be for you to re-submit other much smaller PRs, so that we can look at them individually and see if it makes sense to merge them, an "or all nothing" approach is basically impossible for me to merge.

**Comment by fabiospampinato** [comment]
> Can me me some guideline? which one under voby? which package outside?

If some change has everything to do with reactivity and nothing to do with the DOM it should happen in [oby](https://github.com/vobyjs/oby).

Otherwise it should happen in Voby.

I'd say try to make your changes as minimal as possible compared to the current state of the codebase, and re-submit atomic PRs for individual things, like not a single PR that does many multiple things.

**Comment by wongchichong** [comment]
Hi,

I can't make it work, here are the several issues:

First, I have to use pnpm mono/meta repo, 
this dependencies will load voby from npm, and I can't access npm registry and publish every time I've make changes, 
so I need local symlink. I can run compile & all voby\demo since it use npm's voby.

```json
 "dependencies": {
    "voby": "*"
  }
```

My worker demo can't compile using above settings.
so I use workspace setting: 

```json
 "dependencies": {
    "voby": "workspace:../voby",
  }
```

after "pnpm install", it will create a symlink point to voby folder.

Next, "pnpm compile", "npm compile" or "yarn compile" 
if always give the following error:


```bash
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '~' imported from D:\Developments\meta-voby\node_modules\.pnpm\tsex@2.2.3\node_modules\tsex\dist\index.js
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```

So, i have to type "tsex compile" in terminal directly.
There are several tries by changing ~/ to ./

```bash
S D:\Developments\meta-voby\packages\voby> tsex compile
Failed to rewrite "./jsx/jsx-runtime.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\ssr.js"
Failed to rewrite "./jsx/jsx-runtime.via" import in "D:\Developments\meta-voby\packages\voby\dist\via.js"
Failed to rewrite "~/components/portal.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\components\index.ssr.js"
Failed to rewrite "~/jsx/jsx-runtime.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\ssr\jsx-runtime\index.js"
Failed to rewrite "~/jsx/jsx-runtime.via" import in "D:\Developments\meta-voby\packages\voby\dist\via\jsx-runtime\index.js"
PS D:\Developments\meta-voby\packages\voby> tsex clean
PS D:\Developments\meta-voby\packages\voby> tsex compile
Failed to rewrite "./jsx/jsx-runtime.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\ssr.js"
Failed to rewrite "./jsx/jsx-runtime.via" import in "D:\Developments\meta-voby\packages\voby\dist\via.js"
Failed to rewrite "~/components/portal.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\components\index.ssr.js"
Failed to rewrite "~/jsx/jsx-runtime.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\ssr\jsx-runtime\index.js"
Failed to rewrite "~/jsx/jsx-runtime.via" import in "D:\Developments\meta-voby\packages\voby\dist\via\jsx-runtime\index.js"
PS D:\Developments\meta-voby\packages\voby> tsex compile
Failed to rewrite "./jsx/jsx-runtime.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\ssr.js"
Failed to rewrite "./jsx/jsx-runtime.via" import in "D:\Developments\meta-voby\packages\voby\dist\via.js"
Failed to rewrite "~/components/portal.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\components\index.ssr.js"
Failed to rewrite "~/jsx/jsx-runtime.ssr" import in "D:\Developments\meta-voby\packages\voby\dist\ssr\jsx-runtime\index.js"
Failed to rewrite "../../jsx/jsx-runtime.via" import in "D:\Developments\meta-voby\packages\voby\dist\via\jsx-runtime\index.js"
```

till here, I just temporary ignore those error, something can't transform ~/ in to relative ./ path in dist/*.js files.
then I just run voby\demo to give it a try, and I get 

```bash
3:33:53 PM [vite] Internal server error: failed to resolve "extends":"tsex/tsconfig.json" in D:/Developments/meta-voby/packages/voby/tsconfig.json
  Plugin: vite:esbuild
  File: D:/Developments/meta-voby/packages/voby-demo/demo/playground/index.tsx
      at resolveExtends (file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13212:9)
      at parseExtends (file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13181:34)
      at file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13169:45
      at Array.map (<anonymous>)
      at parseReferences (file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13169:32)
      at async Promise.all (index 1)
      at async parse$f (file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13127:5)
      at async loadTsconfigJsonForFile (file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13664:24)
      at async transformWithEsbuild (file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13348:36)  
      at async TransformContext.transform (file:///D:/Developments/meta-voby/packages/voby-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13483:32)
```

but the web runs, just click away the error, the playground running fine. This playground load voby from npm.

Then I try the voby-via-demo playground, I get this:

```bash
4:02:21 PM [vite] Internal server error: Failed to resolve import "~/types" from "..\..\..\voby\dist\jsx\jsx-runtime.via.jsx". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/Developments/meta-voby/packages/voby/dist/jsx/jsx-runtime.via.jsx:2:7
  1  |  import "~/types";
     |          ^
  2  |  import Fragment from "~/components/fragment";
  3  |  import createElement from "~/methods/create_element.via";
      at formatError (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at normalizeUrl (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
4:02:50 PM [vite] Internal server error: Failed to resolve import "~/types" from "..\..\..\voby\dist\jsx\jsx-runtime.via.jsx". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/Developments/meta-voby/packages/voby/dist/jsx/jsx-runtime.via.jsx:2:7
  1  |  import "~/types";
     |          ^
  2  |  import Fragment from "~/components/fragment";
  3  |  import createElement from "~/methods/create_element.via";
      at formatError (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)  
      at normalizeUrl (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)  
      at async loadAndTransform (file:///D:/Developments/meta-voby/packages/voby-via-demo/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29) (x2)
```

something wrong on ~/ translation again. So I find & replace '~/' to '../' for 1st level folder, '../../' for 2nd folder.
recompile with tsex, ignore those warning, making sure no more ~/ in voby/dist/*.js

re-work the previous journey....

Had tried to merge via into voby, but voby can't differentiate worker/dom environment. So I take out via.
load via before voby worker shall work.

Will issue PR by end of the day.

**Comment by fabiospampinato** [comment]
> this dependencies will load voby from npm, and I can't access npm registry and publish every time I've make changes,

Demos will use the local version of Voby when running in dev mode. Otherwise working on it would be unusable. Like you don't need workspaces, or a monorepo or whatever.

> So, i have to type "tsex compile" in terminal directly.
> There are several tries by changing ~/ to ./

I haven't tested tsex with monorepos, but again, there's no point in using monorepos here.

**Comment by wongchichong** [comment]
Previously like tsconfig path alias too, but it too troublesome working with webpack, have to configure 2 places although plugins available. 

Sometime have to aliasing every github folders that l'm working on. or hard link into node_modules folder which get deleted every clean up.

With workspace, i don't even have to  worry ./ nor ~/ , just the folder name if i want, it automatically link to node_modules with a package.json written in it.

tsex, like babel, that's what our objective, reduce tool chain as much as possible. I even considering publish raw ts files. All build tools claim that are fast still need tsc to do syntax checking and .d.ts generation.We can't bid MS.

i always fallback to tsc --watch if other tools fail me.

Code auto formatting is the big headache for us, just both of us, can't working together. 

You like spaces, I like compact, no { } no ; 

Every file I save is a pull.

I should investigating github diff ignore spaces some time soon.

For now, in this situation, i branch out


Get BlueMail for Android

**Comment by fabiospampinato** [comment]
> Previously like tsconfig path alias too, but it too troublesome working with webpack, have to configure 2 places although plugins available.

Path aliases are an internal thing used only during development, and webpack is unnecessary during development, so I don't see the relevance.

> With workspace, i don't even have to  worry ./ nor ~/ , just the folder name if i want, it automatically link to node_modules with a package.json written in it.

Cool, but I like how things are working already, the current model seems simple enough to me.

> tsex, like babel, that's what our objective, reduce tool chain as much as possible. I even considering publish raw ts files. All build tools claim that are fast still need tsc to do syntax checking and .d.ts generation.We can't bid MS.

That's just an opinionated tool I wrote and use, it's kind of expected for these things to break under Windows or under tools I don't use. Just reporting the issue is usually enough for me to fix them though.

> Code auto formatting is the big headache for us, just both of us, can't working together.
> You like spaces, I like compact, no { } no ;
> Every file I save is a pull.

Yeah better to turn that off if you want your changes merged here.

> I should investigating github diff ignore spaces some time soon.

Sure.

**Comment by wongchichong** [comment]
Initially, i'm thinking fork 1 copy today, merge locally, use notepad++.

Move demo out of voby, keep it small and nice like oby.

Give you a clean copy, hoping you replace everything. But i don't think you are willing to do so.

Without meta repo setup, I can't work on this branch. Those those worker thingy difficult to work in this manner.

I"ve tried to put via.js into voby under 1 compilation, voby can't differentiate worker or DOM env.

I don't mind to put the meta repo under vobyjs namespace.

But after so long discussion, we are still in tsex and ~/ 

I'm moving on. Some twin framework library in very near future.


Get BlueMail for Android

**Comment by fabiospampinato** [comment]
Is there any actual problem with building the project that didn't get fixed now? The tsex stuff should be working now I think. For the worker stuff I'd be open to a PR that improves the situation without reorganizing the entire repo, like importing all the DOM stuff from a single file and turning browser types for all the others or something.

**Pull request closed without merging**
